version: '3.9'
services:
  mysql:
    env_file:
        - example.env
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  web:
    env_file:
      - example.env
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mysql